'Category: Vendor':
  # Source
-   pylav/**/vendor/*
-   pylav/vendor/*
'Category: M3U Parser':
  # Source
-   pylav/extension/m3u/*
'Category: Radio':
-   pylav/extension/radio/*
'Category: CI':
-   .github/workflows/*
'Category: Lavalink':
-   pylav/nodes/*
'Category: i18n':
  # Locale files
-   pylav/**/locales/*
'Category: Filters':
  # Locale files
-   pylav/nodes/api/responses/filters/*
-   pylav/players/filters/*
'Category: Database':
  # Source
-   pylav/storage/*
'Category: Red Utils':
  # Source
-   pylav/vendor/red/*
-   pylav/extension/red/*
'Category: Admin':
-   tools/*
-   .github/*
-   .pre-commit-config.yaml
-   crowdin.yml
-   pyproject.toml
-   README.md
-   info.json
-   CODE_OF_CONDUCT.md
-   LICENSE
-   CLA.md
-   CONTRIBUTING.md
-   .sourcery.yaml
-   bandit.yml
-   SETUP.md
-   mypi.ini
-   CHANGELOG.md
-   poetry.lock
-   poetry.toml
-   .flake8
-   MANIFEST.in
-   .grenrc.yml
-   docker-compose.yml
-   pylav.docker.yml
-   pylav.example.yml
-   application.example.yml
