project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_KEY
base_path: ./
preserve_hierarchy: true
commit_message: Update translations
files:
-   source: pylav/**/messages.pot
    translation: /%original_path%/%locale%.po
    dest: lib/%original_path%/messages.pot
