version: '3.8'
services:
    redbot:
    # Read https://github.com/PhasecoreX/docker-red-discordbot#red-discordbot-v3 for more info
        container_name: redbot
        image: ghcr.io/lifeismana/red-discordbot:extra
        restart: unless-stopped
        volumes:
        -   ./redbot:/data
        -   ./pylav.docker.yaml:/data/pylav.yaml
      # Use the pylav.docker.yaml file from https://github.com/Drapersniper/PyLav/blob/master/docker-compose.yml editing it as necessary.
        -   ./pgsocket:/var/run/postgresql
      # - ./localtracks:/data/localtracks (Localtracks folder)
        environment:
            TOKEN: your_bot_token_goes_here
            PREFIX: '!'
            TZ: Europe/London
            PUID: 1000
            CUSTOM_REDBOT_PACKAGE: git+https://github.com/Cog-Creators/Red-DiscordBot.git
            PYLAV__YAML_CONFIG: /data/pylav.yaml
    postgres:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
        -   ./pgdata:/var/lib/postgresql/data
        -   ./pgsocket:/var/run/postgresql
    ll-node:
        image: drapersniper/pylav-node:master
        restart: always
    # volumes:
    #   - ./localtracks:/data/localtracks (Localtracks folder)
        environment:
            LAVALINK_SERVER_PASSWORD: youshallnotpass # Lavalink Server Password
            _JAVA_OPTIONS: -Xmx4G # The highest amount of RAM which Lavalink is allowed to use
      # Read https://github.com/TopiSenpai/LavaSrc/tree/feature/custom-json-fields#configuration for more info on these setting values
            PLUGINS_LAVASRC_SOURCES_SPOTIFY: false # Enable Spotify source
            PLUGINS_LAVASRC_SPOTIFY_CLIENTID: CHANGE_ME # https://support.heateor.com/get-spotify-client-id-client-secret/
            PLUGINS_LAVASRC_SPOTIFY_CLIENTSECRET: CHANGE_ME # https://support.heateor.com/get-spotify-client-id-client-secret/
            PLUGINS_LAVASRC_SPOTIFY_COUNTRYCODE: US # the country code you want to use for filtering the artists top tracks and language. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

            PLUGINS_LAVASRC_SOURCES_APPLEMUSIC: true # Enable Apple Music source
            PLUGINS_LAVASRC_APPLEMUSIC_COUNTRYCODE: US # the country code you want to use for filtering the artists top tracks and language. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
            PLUGINS_LAVASRC_APPLEMUSIC_MEDIAAPITOKEN: # Not necessary, Can be used to bypass the auto token fetching which is likely to break again in the future

            PLUGINS_LAVASRC_SOURCES_YANDEXMUSIC: false # Enable Yandex Music source
            PLUGINS_LAVASRC_YANDEXMUSIC_ACCESSTOKEN: # the token used for accessing the yandex music api. See https://github.com/TopiSenpai/LavaSrc#yandex-music

            PLUGINS_LAVASRC_SOURCES_DEEZER: true # Enable Deezer source

            # These are not necessary but can be used to bypass the auto token fetching which is likely to break again in the future
            LAVALINK_SERVER_YOUTUBECONFIG_EMAIL:  # Google account email to use to bypass age restrictions
            LAVALINK_SERVER_YOUTUBECONFIG_PASSWORD:  # Google account password to use to bypass age restrictions
