[tool.isort]
profile = "black"
line_length = 120
py_version = 39
known_third_party=["aiohttp", "ujson", "red_commons", "discord", "sqlalchemy", "cached_property", "dateutils", "appdirs", "yaml", "aiopath", "aiopath", "tabulate", "humanize"]
known_local_folder=["pylav"]

[tool.black]
line-length = 120
target-version = ['py39']


[tool.autopep8]
max_line_length = 120
ignore = "E203,E501"
in-place = true
recursive = true
aggressive = 3
